/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Collection__factory } from "./Collection__factory";
export { Main__factory } from "./Main__factory";
