/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Collection } from "./Collection";
export type { Main } from "./Main";
export * as factories from "./factories";
export { Collection__factory } from "./factories/Collection__factory";
export { Main__factory } from "./factories/Main__factory";
